/*
 * temp.java
 *
 * Created on 31 de agosto de 2001, 03:37 PM
 */

package hydroScalingAPI.util.plot;

/**
 *
 * @author  olver
 * @version 
 */
public class temp extends javax.swing.JDialog {

    /** Creates new form temp */
    hydroScalingAPI.util.plot.XYJPanel p;
    public temp(java.awt.Frame parent,boolean modal) {
        super (parent, modal);
        initComponents ();
        pack ();
        
        setBounds(0,0, 500, 500);
        double [] datos = {1,3,4,2,54,6,5,3,54,6,45,23,12,45,4,33,4,2,23,9,6};
        p = new hydroScalingAPI.util.plot.XYJPanel(datos,datos,"A Plot","Years","Precipitation [mm]",-9999);
        jPanel1.add(p);
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents () {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel ();
        jPanel2 = new javax.swing.JPanel ();
        jButton1 = new javax.swing.JButton ();
        addWindowListener (new java.awt.event.WindowAdapter () {
            public void windowClosing (java.awt.event.WindowEvent evt) {
                closeDialog (evt);
            }
        }
        );

        jPanel1.setLayout (new java.awt.GridLayout (1, 2));

  
          jPanel1.add (jPanel2);
  

        getContentPane ().add (jPanel1, java.awt.BorderLayout.CENTER);

        jButton1.setText ("jButton1");
        jButton1.addActionListener (new java.awt.event.ActionListener () {
            public void actionPerformed (java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed (evt);
            }
        }
        );


        getContentPane ().add (jButton1, java.awt.BorderLayout.SOUTH);

    }//GEN-END:initComponents

  private void jButton1ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// Add your handling code here:
    jPanel2.getGraphics().drawImage((java.awt.Image)p.getImage(),0,0,null);
  }//GEN-LAST:event_jButton1ActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible (false);
        dispose ();
        System.exit(0);
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main (String args[]) {
        new temp (new javax.swing.JFrame (), true).setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}