/*
 * ChangeDBName.java
 *
 * Created on March 7, 2007, 12:07 PM
 */

package hydroScalingAPI.mainGUI.widgets;

/**
 *
 * @author  ricardo
 */
public class InfoRequest extends javax.swing.JDialog {
    
    private hydroScalingAPI.mainGUI.ParentGUI mainGUI;
    
    /** Creates new form ChangeDBName */
    public InfoRequest(hydroScalingAPI.mainGUI.ParentGUI parent) {
        super(parent, true);
        initComponents();
        mainGUI=parent;
        
        setBounds(0,0, 400, 60);
        java.awt.Rectangle marcoParent=mainGUI.getBounds();
        java.awt.Rectangle thisMarco=this.getBounds();
        setBounds(marcoParent.x+marcoParent.width/2-thisMarco.width/2,marcoParent.y+marcoParent.height/2-thisMarco.height/2,thisMarco.width,thisMarco.height);
        
        nameTextField.setText("");
        
    }
    
    public String getBaseName(){
        return nameTextField.getText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        nameTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        applyChange = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Base Name");
        nameTextField.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        nameTextField.setText("jTextField1");
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        getContentPane().add(nameTextField, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout());

        applyChange.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        applyChange.setText("Set");
        applyChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyChangeActionPerformed(evt);
            }
        });

        jPanel1.add(applyChange);

        cancel.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jPanel1.add(cancel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        nameTextField.setText("");
        setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        setVisible(false);
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void applyChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyChangeActionPerformed
        setVisible(false);
    }//GEN-LAST:event_applyChangeActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyChange;
    private javax.swing.JButton cancel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameTextField;
    // End of variables declaration//GEN-END:variables
    
}
