/*
 * TimeSeriesViewer.java
 *
 * Created on June 26, 2003, 10:00 AM
 */

package hydroScalingAPI.modules.analysis_TS.widgets;

/**
 *
 * @author Ricardo Mantilla
 */
public class TimeSeriesViewer extends javax.swing.JDialog {
    
    private hydroScalingAPI.mainGUI.ParentGUI mainFrame;
    
    private hydroScalingAPI.util.plot.XYJPanel p;
    
    /** Creates new form TimeSeriesViewer */
    public TimeSeriesViewer(hydroScalingAPI.mainGUI.ParentGUI parent, hydroScalingAPI.io.MetaGauge oneGauge) {
        super(parent, true);
        mainFrame=parent;
        initComponents();
        pack ();
        
        setBounds(0,0, 600, 350);
        java.awt.Rectangle marcoParent=mainFrame.getBounds();
        java.awt.Rectangle thisMarco=this.getBounds();
        setBounds(marcoParent.x+marcoParent.width/2-thisMarco.width/2,marcoParent.y+marcoParent.height/2-thisMarco.height/2,thisMarco.width,thisMarco.height);
        
        try{
            double [][] data = oneGauge.getTimeAndData();
            p = new hydroScalingAPI.util.plot.XYJPanel(data[0],data[1],oneGauge.toString(),"Years",oneGauge.getLabel(),-9999);
            getContentPane().add(p);
        } catch (java.io.IOException IOE){
            System.err.println("Failed loading data");
            System.err.println(IOE);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        hydroScalingAPI.mainGUI.ParentGUI tempFrame=new hydroScalingAPI.mainGUI.ParentGUI();
        new visad.util.Delay(1000);
        java.util.Vector categories=new java.util.Vector();
        java.util.Vector values=new java.util.Vector();
        java.util.Vector conditions=new java.util.Vector();
        
        categories.add("[state]");
        values.add("Arizona");
        conditions.add(new Integer(0));
        categories.add("[type]");
        values.add("Streamflow");
        conditions.add(new Integer(0));
        
        hydroScalingAPI.io.MetaGauge[] queryResult = tempFrame.getGaugesManager().findGauges(categories, values, conditions);
        new TimeSeriesViewer(tempFrame,queryResult[0]).setVisible(true);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
