/*
 * ChangeDBName.java
 *
 * Created on March 7, 2007, 12:07 PM
 */

package hydroScalingAPI.subGUIs.widgets;

/**
 *
 * @author  ricardo
 */
public class ChangeDBName extends javax.swing.JDialog {
    
    private hydroScalingAPI.mainGUI.ParentGUI mainGUI;
    
    /** Creates new form ChangeDBName */
    public ChangeDBName(hydroScalingAPI.mainGUI.ParentGUI parent) {
        super(parent, true);
        initComponents();
        mainGUI=parent;
        
        setBounds(0,0, 400, 60);
        java.awt.Rectangle marcoParent=mainGUI.getBounds();
        java.awt.Rectangle thisMarco=this.getBounds();
        setBounds(marcoParent.x+marcoParent.width/2-thisMarco.width/2,marcoParent.y+marcoParent.height/2-thisMarco.height/2,thisMarco.width,thisMarco.height);
        
        try{
                java.io.FileReader reader = new java.io.FileReader(mainGUI.getInfoManager().dataBaseNamePath);
                java.io.BufferedReader buffer=new java.io.BufferedReader(reader);
                nameTextField.setText(buffer.readLine());
                buffer.close();
            } catch (java.io.IOException IOE){
                System.err.println("An Error has ocurred while reading name.txt");
                IOE.printStackTrace();
            }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        nameTextField = new javax.swing.JTextField();
        applyChange = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        nameTextField.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        nameTextField.setText("jTextField1");
        getContentPane().add(nameTextField, java.awt.BorderLayout.CENTER);

        applyChange.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        applyChange.setText("Rename");
        applyChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyChangeActionPerformed(evt);
            }
        });

        getContentPane().add(applyChange, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void applyChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyChangeActionPerformed
        try{
            java.io.BufferedWriter metaBuffer = new java.io.BufferedWriter(new java.io.FileWriter(mainGUI.getInfoManager().dataBaseNamePath));
            metaBuffer.write(nameTextField.getText()+"\n");
            metaBuffer.close();
            mainGUI.updateDBNameLabel(nameTextField.getText());
            setVisible(false);
            dispose();
        } catch (java.io.IOException ioe){
            System.err.println("Failed renaming the Database");
            ioe.printStackTrace();
        }
    }//GEN-LAST:event_applyChangeActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyChange;
    private javax.swing.JTextField nameTextField;
    // End of variables declaration//GEN-END:variables
    
}
