/*
 * ScaleControlPanel.java
 *
 * Created on July 2, 2003, 11:46 AM
 */

package hydroScalingAPI.subGUIs.widgets;

/**
 *
 * @author  ricardo
 */
public class ScaleControlPanel extends javax.swing.JPanel {
    
    private visad.AxisScale scale;
    private visad.ScalarMap myMap;
    
    /** Creates new form ScaleControlPanel */
    public ScaleControlPanel(visad.ScalarMap map) {
        myMap=map;
        scale = map.getAxisScale();
        if (scale == null) return;
        
        initComponents();
        
        setUpGUI();
        
        
    }
    
    private void setUpGUI(){
        
        String scalarName = myMap.getScalarName();
        setBorder(new javax.swing.border.TitledBorder(null, scalarName + " AxisScale Control", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10)));
        
        
        java.awt.GraphicsEnvironment ge =
        java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment();
        
        java.awt.Font[] fonts = ge.getAllFonts();
        
        for(int i=0;i<fonts.length;i++){
            String fn = fonts[i].getFontName();
            fontControl.addItem( fn );
        }
        
        fontControl.addItem("HersheyFont.futural");
        fontControl.addItem("HersheyFont.futuram");
        fontControl.addItem("HersheyFont.cursive");
        fontControl.addItem("HersheyFont.timesr");
        fontControl.addItem("HersheyFont.timesrb");
        fontControl.addItem("HersheyFont.rowmans");
        fontControl.addItem("HersheyFont.rowmant");
        
        fontControl.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fontControlItemStateChanged(evt);
            }
        });
        
        snapCheck.setSelected(scale.getSnapToBox());
        visibleCheck.setSelected(scale.isVisible());
        labelAllCheck.setSelected(scale.getLabelAllTicks());
        
        axisNameControl.setText(scalarName);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        axisNameControl = new javax.swing.JTextField();
        sizeControl = new javax.swing.JSlider();
        fontControl = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        fontColorControl = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        sidePrimary = new javax.swing.JRadioButton();
        sideSecondary = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        tickPrimary = new javax.swing.JRadioButton();
        tickSecondary = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        snapCheck = new javax.swing.JCheckBox();
        visibleCheck = new javax.swing.JCheckBox();
        labelAllCheck = new javax.swing.JCheckBox();

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.TitledBorder(null, "Control", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10)));
        jPanel1.setLayout(new java.awt.GridLayout(7, 1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 10));
        jLabel1.setText("Title : ");
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 10));
        jLabel2.setText("Title/Label Size : ");
        jPanel1.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 10));
        jLabel3.setText("Label Font : ");
        jPanel1.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 10));
        jLabel4.setText("Color : ");
        jPanel1.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 10));
        jLabel5.setText("Axis Side : ");
        jPanel1.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 10));
        jLabel6.setText("Tick Orientation : ");
        jPanel1.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 10));
        jLabel7.setText("Options : ");
        jPanel1.add(jLabel7);

        add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setLayout(new java.awt.GridLayout(7, 1));

        axisNameControl.setFont(new java.awt.Font("Dialog", 0, 10));
        axisNameControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                axisNameControlActionPerformed(evt);
            }
        });

        jPanel2.add(axisNameControl);

        sizeControl.setFont(new java.awt.Font("Dialog", 0, 10));
        sizeControl.setMajorTickSpacing(10);
        sizeControl.setMaximum(50);
        sizeControl.setMinorTickSpacing(2);
        sizeControl.setPaintTicks(true);
        sizeControl.setValue(12);
        sizeControl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sizeControlStateChanged(evt);
            }
        });

        jPanel2.add(sizeControl);

        jPanel2.add(fontControl);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 10));
        jLabel8.setText("Select from Palette ");
        jPanel6.add(jLabel8);

        fontColorControl.setBackground(new java.awt.Color(255, 255, 255));
        fontColorControl.setFont(new java.awt.Font("Dialog", 1, 10));
        fontColorControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontColorControlActionPerformed(evt);
            }
        });

        jPanel6.add(fontColorControl);

        jPanel2.add(jPanel6);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        sidePrimary.setFont(new java.awt.Font("Dialog", 0, 10));
        sidePrimary.setSelected(true);
        sidePrimary.setText("Primary");
        buttonGroup1.add(sidePrimary);
        sidePrimary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidePrimaryActionPerformed(evt);
            }
        });

        jPanel3.add(sidePrimary);

        sideSecondary.setFont(new java.awt.Font("Dialog", 0, 10));
        sideSecondary.setText("Secondary");
        buttonGroup1.add(sideSecondary);
        sideSecondary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideSecondaryActionPerformed(evt);
            }
        });

        jPanel3.add(sideSecondary);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        tickPrimary.setFont(new java.awt.Font("Dialog", 0, 10));
        tickPrimary.setSelected(true);
        tickPrimary.setText("Primary");
        buttonGroup2.add(tickPrimary);
        tickPrimary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tickPrimaryActionPerformed(evt);
            }
        });

        jPanel4.add(tickPrimary);

        tickSecondary.setFont(new java.awt.Font("Dialog", 0, 10));
        tickSecondary.setText("Secondary");
        buttonGroup2.add(tickSecondary);
        tickSecondary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tickSecondaryActionPerformed(evt);
            }
        });

        jPanel4.add(tickSecondary);

        jPanel2.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 3));

        snapCheck.setFont(new java.awt.Font("Dialog", 0, 10));
        snapCheck.setText("Snap");
        snapCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snapCheckActionPerformed(evt);
            }
        });

        jPanel5.add(snapCheck);

        visibleCheck.setFont(new java.awt.Font("Dialog", 0, 10));
        visibleCheck.setText("Visible");
        visibleCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visibleCheckActionPerformed(evt);
            }
        });

        jPanel5.add(visibleCheck);

        labelAllCheck.setFont(new java.awt.Font("Dialog", 0, 10));
        labelAllCheck.setText("Label All");
        labelAllCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelAllCheckActionPerformed(evt);
            }
        });

        jPanel5.add(labelAllCheck);

        jPanel2.add(jPanel5);

        add(jPanel2, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
        
    private void labelAllCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelAllCheckActionPerformed
        scale.setLabelAllTicks(((javax.swing.JCheckBox)evt.getSource()).isSelected());
    }//GEN-LAST:event_labelAllCheckActionPerformed
    
    private void visibleCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visibleCheckActionPerformed
        scale.setVisible(((javax.swing.JCheckBox)evt.getSource()).isSelected());
    }//GEN-LAST:event_visibleCheckActionPerformed
    
    private void snapCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snapCheckActionPerformed
        scale.setSnapToBox(((javax.swing.JCheckBox)evt.getSource()).isSelected());
    }//GEN-LAST:event_snapCheckActionPerformed
    
    private void tickSecondaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tickSecondaryActionPerformed
        scale.setTickOrientation(scale.SECONDARY);
    }//GEN-LAST:event_tickSecondaryActionPerformed
    
    private void tickPrimaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tickPrimaryActionPerformed
        scale.setTickOrientation(scale.PRIMARY);
    }//GEN-LAST:event_tickPrimaryActionPerformed
    
    private void sideSecondaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideSecondaryActionPerformed
        scale.setSide(scale.SECONDARY);
    }//GEN-LAST:event_sideSecondaryActionPerformed
    
    private void sidePrimaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidePrimaryActionPerformed
        scale.setSide(scale.PRIMARY);
    }//GEN-LAST:event_sidePrimaryActionPerformed
    
    private void fontColorControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontColorControlActionPerformed
        javax.swing.JButton button = (javax.swing.JButton) evt.getSource();
        java.awt.Color newColor =
        javax.swing.JColorChooser.showDialog(
        this,
        "Set AxisScale Color",
        fontColorControl.getBackground());
        if (newColor != null) {
            scale.setColor(newColor);
            fontColorControl.setBackground(newColor);
        }
    }//GEN-LAST:event_fontColorControlActionPerformed
    
    private void sizeControlStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sizeControlStateChanged
        javax.swing.JSlider slider = (javax.swing.JSlider) evt.getSource();
        if (!slider.getValueIsAdjusting()) {
            scale.setLabelSize(slider.getValue());
        }
    }//GEN-LAST:event_sizeControlStateChanged
    
    private void axisNameControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_axisNameControlActionPerformed
        scale.setTitle(((javax.swing.JTextField)evt.getSource()).getText());
    }//GEN-LAST:event_axisNameControlActionPerformed
    
    private void fontControlItemStateChanged(java.awt.event.ItemEvent evt) {
        if (evt.getStateChange() == 1){
            String fontName =(String) ((javax.swing.JComboBox)evt.getSource()).getSelectedItem();
            
            if (fontName.startsWith("Hershey")) {
                visad.util.HersheyFont font = new visad.util.HersheyFont(
                fontName.substring(fontName.indexOf(".")+1) );
                scale.setFont(font);
                sizeControl.setValue(12);  // HersheyFonts are 12 point
                
            } else {
                java.awt.Font font = java.awt.Font.decode(fontName);
                int fSize=sizeControl.getValue();
                font = font.deriveFont((float) fSize);
                scale.setFont(font);
                sizeControl.setValue(font.getSize());
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField axisNameControl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton fontColorControl;
    private javax.swing.JComboBox fontControl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JCheckBox labelAllCheck;
    private javax.swing.JRadioButton sidePrimary;
    private javax.swing.JRadioButton sideSecondary;
    private javax.swing.JSlider sizeControl;
    private javax.swing.JCheckBox snapCheck;
    private javax.swing.JRadioButton tickPrimary;
    private javax.swing.JRadioButton tickSecondary;
    private javax.swing.JCheckBox visibleCheck;
    // End of variables declaration//GEN-END:variables
    
}
