/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TabbedUSGSDownloadWizard.java
 *
 * Created on Mar 31, 2009, 1:11:41 AM
 */
package hydroScalingAPI.subGUIs.widgets;

/**
 *
 * @author Eric Osgood
 */
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.util.*;
import javax.swing.table.*;

/**
 *A client to download data from the USGS water.usgs.gov website.
 * The client contains 3 tabs, the first is a visual representation of water amounts in the USA.  The second is a tab to download data, the third is as well.
 * @author Eric Osgood
 */
public class TabbedUSGSDownloadWizard extends javax.swing.JDialog {

    private hydroScalingAPI.subGUIs.widgets.ImportUSGSWeb myQueryManager;
    private javax.swing.JCheckBox[] listOfCheckBoxes;

    /** Creates new form TabbedUSGSDownloadWizard
     * @param parent 
     * @param modal
     */
    public TabbedUSGSDownloadWizard(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setTitle("Import USGS data from Internet");
        myQueryManager = new hydroScalingAPI.subGUIs.widgets.ImportUSGSWeb();

        System.out.println("line 40");

        if (!myQueryManager.connectionTest()) {
            Object[] options = {"OK"};
            if (JOptionPane.showOptionDialog(this, "Connection to Internet Failed!", "Attention", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]) == 1) {
                return;
            }
            return;
        }
        System.out.println("line 47");

        initComponents();
        setLocation(220, 200);
        System.out.println("line 52  components running");

        java.util.Calendar todaysDate = java.util.Calendar.getInstance();

        System.out.println((todaysDate.get(todaysDate.YEAR)) + "-" + (todaysDate.get(todaysDate.MONTH) + 1) + "-" + todaysDate.get(todaysDate.DAY_OF_MONTH));
        EndText.setText((todaysDate.get(todaysDate.YEAR)) + "-" + (todaysDate.get(todaysDate.MONTH) + 1) + "-" + todaysDate.get(todaysDate.DAY_OF_MONTH));

        setVisible(true);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Map = new javax.swing.JPanel();
        USGSMap = new javax.swing.JLabel();
        USGSLegend = new javax.swing.JLabel();
        RegionState = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NorthEast = new javax.swing.JCheckBox();
        South = new javax.swing.JCheckBox();
        MidWest = new javax.swing.JCheckBox();
        West = new javax.swing.JCheckBox();
        AllReg = new javax.swing.JCheckBox();
        AllST = new javax.swing.JCheckBox();
        AL = new javax.swing.JCheckBox();
        AK = new javax.swing.JCheckBox();
        AZ = new javax.swing.JCheckBox();
        AR = new javax.swing.JCheckBox();
        CA = new javax.swing.JCheckBox();
        CO = new javax.swing.JCheckBox();
        CT = new javax.swing.JCheckBox();
        DE = new javax.swing.JCheckBox();
        DC = new javax.swing.JCheckBox();
        FL = new javax.swing.JCheckBox();
        GA = new javax.swing.JCheckBox();
        HI = new javax.swing.JCheckBox();
        ID = new javax.swing.JCheckBox();
        IL = new javax.swing.JCheckBox();
        IN = new javax.swing.JCheckBox();
        IA = new javax.swing.JCheckBox();
        KS = new javax.swing.JCheckBox();
        KY = new javax.swing.JCheckBox();
        LA = new javax.swing.JCheckBox();
        ME = new javax.swing.JCheckBox();
        MD = new javax.swing.JCheckBox();
        MA = new javax.swing.JCheckBox();
        MI = new javax.swing.JCheckBox();
        MN = new javax.swing.JCheckBox();
        MS = new javax.swing.JCheckBox();
        MO = new javax.swing.JCheckBox();
        MT = new javax.swing.JCheckBox();
        NE = new javax.swing.JCheckBox();
        NV = new javax.swing.JCheckBox();
        NH = new javax.swing.JCheckBox();
        NJ = new javax.swing.JCheckBox();
        NM = new javax.swing.JCheckBox();
        NY = new javax.swing.JCheckBox();
        NC = new javax.swing.JCheckBox();
        ND = new javax.swing.JCheckBox();
        OH = new javax.swing.JCheckBox();
        OK = new javax.swing.JCheckBox();
        OR = new javax.swing.JCheckBox();
        PA = new javax.swing.JCheckBox();
        RI = new javax.swing.JCheckBox();
        SC = new javax.swing.JCheckBox();
        SD = new javax.swing.JCheckBox();
        TN = new javax.swing.JCheckBox();
        TX = new javax.swing.JCheckBox();
        UT = new javax.swing.JCheckBox();
        VT = new javax.swing.JCheckBox();
        VA = new javax.swing.JCheckBox();
        WA = new javax.swing.JCheckBox();
        WV = new javax.swing.JCheckBox();
        WI = new javax.swing.JCheckBox();
        WY = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        BoundingBox = new javax.swing.JPanel();
        EastLon2 = new javax.swing.JTextField();
        EastLon = new javax.swing.JLabel();
        NorthLat2 = new javax.swing.JTextField();
        NorthLat = new javax.swing.JLabel();
        WestLon2 = new javax.swing.JTextField();
        WestLon = new javax.swing.JLabel();
        SouthLat2 = new javax.swing.JTextField();
        SouthLat = new javax.swing.JLabel();
        GetBoundSites = new javax.swing.JButton();
        getCoordFile = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        boundInstruct = new javax.swing.JTextArea();
        boundPic = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        DownloadData = new javax.swing.JButton();
        SiteCounterInfo = new javax.swing.JLabel();
        EndDate = new javax.swing.JLabel();
        StartDate = new javax.swing.JLabel();
        EndText = new javax.swing.JTextField();
        StartText = new javax.swing.JTextField();
        CheckAll = new javax.swing.JLabel();
        UncheckAll = new javax.swing.JLabel();
        CheckMarked = new javax.swing.JLabel();
        Note = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        USGSMap.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("http://water.usgs.gov/waterwatch/images/real/us/realb.gif")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());

        USGSLegend.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("http://water.usgs.gov/waterwatch/images/map_legends/ptile_dot.gif")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());

        org.jdesktop.layout.GroupLayout MapLayout = new org.jdesktop.layout.GroupLayout(Map);
        Map.setLayout(MapLayout);
        MapLayout.setHorizontalGroup(
            MapLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(MapLayout.createSequentialGroup()
                .addContainerGap()
                .add(USGSMap)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(USGSLegend)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        MapLayout.setVerticalGroup(
            MapLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(MapLayout.createSequentialGroup()
                .addContainerGap()
                .add(MapLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(USGSMap)
                    .add(USGSLegend))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Map", Map);

        jLabel1.setText("What region or regions?");

        jLabel2.setText("What state or states?");

        NorthEast.setText("NorthEast");
        NorthEast.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NorthEastItemStateChanged(evt);
            }
        });

        South.setText("South");
        South.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SouthItemStateChanged(evt);
            }
        });

        MidWest.setText("MidWest");
        MidWest.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MidWestItemStateChanged(evt);
            }
        });

        West.setText("West");
        West.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                WestItemStateChanged(evt);
            }
        });

        AllReg.setText("All");
        AllReg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AllRegItemStateChanged(evt);
            }
        });

        AllST.setText("All");
        AllST.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AllSTItemStateChanged(evt);
            }
        });

        AL.setText("AL");
        AL.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ALItemStateChanged(evt);
            }
        });

        AK.setText("AK");
        AK.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AKItemStateChanged(evt);
            }
        });

        AZ.setText("AZ");
        AZ.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AZItemStateChanged(evt);
            }
        });

        AR.setText("AR");
        AR.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ARItemStateChanged(evt);
            }
        });

        CA.setText("CA");
        CA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CAItemStateChanged(evt);
            }
        });

        CO.setText("CO");
        CO.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                COItemStateChanged(evt);
            }
        });

        CT.setText("CT");
        CT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CTItemStateChanged(evt);
            }
        });

        DE.setText("DE");
        DE.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DEItemStateChanged(evt);
            }
        });

        DC.setText("DC");
        DC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DCItemStateChanged(evt);
            }
        });

        FL.setText("FL");
        FL.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FLItemStateChanged(evt);
            }
        });

        GA.setText("GA");
        GA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                GAItemStateChanged(evt);
            }
        });

        HI.setText("HI");
        HI.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                HIItemStateChanged(evt);
            }
        });

        ID.setText("ID");
        ID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                IDItemStateChanged(evt);
            }
        });

        IL.setText("IL");
        IL.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ILItemStateChanged(evt);
            }
        });

        IN.setText("IN");
        IN.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                INItemStateChanged(evt);
            }
        });

        IA.setText("IA");
        IA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                IAItemStateChanged(evt);
            }
        });

        KS.setText("KS");
        KS.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                KSItemStateChanged(evt);
            }
        });

        KY.setText("KY");
        KY.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                KYItemStateChanged(evt);
            }
        });

        LA.setText("LA");
        LA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                LAItemStateChanged(evt);
            }
        });

        ME.setText("ME");
        ME.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MEItemStateChanged(evt);
            }
        });

        MD.setText("MD");
        MD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MDItemStateChanged(evt);
            }
        });

        MA.setText("MA");
        MA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MAItemStateChanged(evt);
            }
        });

        MI.setText("MI");
        MI.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MIItemStateChanged(evt);
            }
        });

        MN.setText("MN");
        MN.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MNItemStateChanged(evt);
            }
        });

        MS.setText("MS");
        MS.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MSItemStateChanged(evt);
            }
        });

        MO.setText("MO");
        MO.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MOItemStateChanged(evt);
            }
        });

        MT.setText("MT");
        MT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MTItemStateChanged(evt);
            }
        });

        NE.setText("NE");
        NE.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NEItemStateChanged(evt);
            }
        });

        NV.setText("NV");
        NV.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NVItemStateChanged(evt);
            }
        });

        NH.setText("NH");
        NH.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NHItemStateChanged(evt);
            }
        });

        NJ.setText("NJ");
        NJ.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NJItemStateChanged(evt);
            }
        });

        NM.setText("NM");
        NM.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NMItemStateChanged(evt);
            }
        });

        NY.setText("NY");
        NY.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NYItemStateChanged(evt);
            }
        });

        NC.setText("NC");
        NC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NCItemStateChanged(evt);
            }
        });

        ND.setText("ND");
        ND.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NDItemStateChanged(evt);
            }
        });

        OH.setText("OH");
        OH.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                OHItemStateChanged(evt);
            }
        });

        OK.setText("OK");
        OK.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                OKItemStateChanged(evt);
            }
        });

        OR.setText("OR");
        OR.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ORItemStateChanged(evt);
            }
        });

        PA.setText("PA");
        PA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                PAItemStateChanged(evt);
            }
        });

        RI.setText("RI");
        RI.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RIItemStateChanged(evt);
            }
        });

        SC.setText("SC");
        SC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SCItemStateChanged(evt);
            }
        });

        SD.setText("SD");
        SD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SDItemStateChanged(evt);
            }
        });

        TN.setText("TN");
        TN.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TNItemStateChanged(evt);
            }
        });

        TX.setText("TX");
        TX.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TXItemStateChanged(evt);
            }
        });

        UT.setText("UT");
        UT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                UTItemStateChanged(evt);
            }
        });

        VT.setText("VT");
        VT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                VTItemStateChanged(evt);
            }
        });

        VA.setText("VA");
        VA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                VAItemStateChanged(evt);
            }
        });

        WA.setText("WA");
        WA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                WAItemStateChanged(evt);
            }
        });

        WV.setText("WV");
        WV.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                WVItemStateChanged(evt);
            }
        });

        WI.setText("WI");
        WI.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                WIItemStateChanged(evt);
            }
        });

        WY.setText("WY");
        WY.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                WYItemStateChanged(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eric Osgood.EricOsgood-PC\\Documents\\NetBeansProjects\\Cuencas\\cuencas\\src\\hydroScalingAPI\\subGUIs\\configuration\\icons\\USGSLittleRiver.jpg")); // NOI18N

        org.jdesktop.layout.GroupLayout RegionStateLayout = new org.jdesktop.layout.GroupLayout(RegionState);
        RegionState.setLayout(RegionStateLayout);
        RegionStateLayout.setHorizontalGroup(
            RegionStateLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(RegionStateLayout.createSequentialGroup()
                .addContainerGap()
                .add(RegionStateLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(West)
                    .add(AllReg)
                    .add(MidWest)
                    .add(South)
                    .add(NorthEast))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(RegionStateLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(RegionStateLayout.createSequentialGroup()
                        .add(RegionStateLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(AZ)
                            .add(AR)
                            .add(CA)
                            .add(AK)
                            .add(AllST)
                            .add(AL))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(RegionStateLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(CO)
                            .add(CT)
                            .add(DE)
                            .add(DC)
                            .add(FL)
                            .add(GA))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(RegionStateLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(IA)
                            .add(KS)
                            .add(IL)
                            .add(IN)
                            .add(HI)
                            .add(ID)))
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(RegionStateLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(MI)
                    .add(MA)
                    .add(MD)
                    .add(ME)
                    .add(LA)
                    .add(KY))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(RegionStateLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(NV)
                    .add(NE)
                    .add(MT)
                    .add(MO)
                    .add(MS)
                    .add(MN))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(RegionStateLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(NC)
                    .add(ND)
                    .add(NY)
                    .add(NM)
                    .add(NH)
                    .add(NJ))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(RegionStateLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(SC)
                    .add(RI)
                    .add(PA)
                    .add(OR)
                    .add(OK)
                    .add(OH))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(RegionStateLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(SD)
                    .add(TN)
                    .add(TX)
                    .add(UT)
                    .add(VT)
                    .add(VA))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(RegionStateLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(WY)
                    .add(WI)
                    .add(WV)
                    .add(WA))
                .add(18, 18, 18)
                .add(jLabel9)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        RegionStateLayout.setVerticalGroup(
            RegionStateLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(RegionStateLayout.createSequentialGroup()
                .add(RegionStateLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(RegionStateLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(RegionStateLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(RegionStateLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(RegionStateLayout.createSequentialGroup()
                                .add(AllReg)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(West)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(MidWest)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(South))
                            .add(RegionStateLayout.createSequentialGroup()
                                .add(RegionStateLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(AllST, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(CO)
                                    .add(HI)
                                    .add(KY)
                                    .add(MN)
                                    .add(NH)
                                    .add(OH)
                                    .add(SD)
                                    .add(WA))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(RegionStateLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(AL)
                                    .add(CT)
                                    .add(ID)
                                    .add(LA)
                                    .add(MS)
                                    .add(NJ)
                                    .add(OK)
                                    .add(TN)
                                    .add(WV))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(RegionStateLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(AK)
                                    .add(DE)
                                    .add(IL)
                                    .add(ME)
                                    .add(MO)
                                    .add(NM)
                                    .add(OR)
                                    .add(TX)
                                    .add(WI))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(RegionStateLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(AZ)
                                    .add(DC)
                                    .add(IN)
                                    .add(MD)
                                    .add(MT)
                                    .add(NY)
                                    .add(PA)
                                    .add(UT)
                                    .add(WY))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(RegionStateLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(AR)
                                    .add(FL)
                                    .add(IA)
                                    .add(MA)
                                    .add(NE)
                                    .add(NC)
                                    .add(RI)
                                    .add(VT)
                                    .add(NorthEast))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(RegionStateLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(CA)
                                    .add(GA)
                                    .add(KS)
                                    .add(MI)
                                    .add(NV)
                                    .add(ND)
                                    .add(SC)
                                    .add(VA)))))
                    .add(RegionStateLayout.createSequentialGroup()
                        .add(32, 32, 32)
                        .add(jLabel9)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Region/State", RegionState);

        EastLon2.setText("180");

        EastLon.setText("Easternmost Longitude");

        NorthLat2.setText("90");

        NorthLat.setText("Northernmost Latitude");

        WestLon2.setText("-180");

        WestLon.setText("Westernmost Longitude");

        SouthLat2.setText("-90");

        SouthLat.setText("Southernmost Latitude");

        GetBoundSites.setText("Get Sites");
        GetBoundSites.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                GetBoundSitesMouseReleased(evt);
            }
        });

        getCoordFile.setText("Get Coordinate from File");
        getCoordFile.setToolTipText("Get coordinates from metaDEM");
        getCoordFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getCoordFileActionPerformed(evt);
            }
        });

        boundInstruct.setColumns(20);
        boundInstruct.setEditable(false);
        boundInstruct.setRows(5);
        boundInstruct.setText("Enter coordinates into boxes\nin decimal degree format then\npress \"Get Data\".");
        jScrollPane2.setViewportView(boundInstruct);

        boundPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hydroScalingAPI/subGUIs/configuration/icons/bound.gif"))); // NOI18N

        org.jdesktop.layout.GroupLayout BoundingBoxLayout = new org.jdesktop.layout.GroupLayout(BoundingBox);
        BoundingBox.setLayout(BoundingBoxLayout);
        BoundingBoxLayout.setHorizontalGroup(
            BoundingBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(BoundingBoxLayout.createSequentialGroup()
                .addContainerGap()
                .add(BoundingBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, BoundingBoxLayout.createSequentialGroup()
                        .add(BoundingBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(BoundingBoxLayout.createSequentialGroup()
                                .add(69, 69, 69)
                                .add(boundPic)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(SouthLat))
                            .add(BoundingBoxLayout.createSequentialGroup()
                                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 240, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 163, Short.MAX_VALUE)
                                .add(NorthLat)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(BoundingBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                            .add(NorthLat2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(SouthLat2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(337, 337, 337))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, BoundingBoxLayout.createSequentialGroup()
                        .add(WestLon)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(WestLon2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(211, 211, 211)
                        .add(EastLon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 151, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(EastLon2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(102, 102, 102))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, BoundingBoxLayout.createSequentialGroup()
                        .add(getCoordFile)
                        .add(96, 96, 96)
                        .add(GetBoundSites)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BoundingBoxLayout.linkSize(new java.awt.Component[] {EastLon2, NorthLat2, SouthLat2, WestLon2}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        BoundingBoxLayout.setVerticalGroup(
            BoundingBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(BoundingBoxLayout.createSequentialGroup()
                .addContainerGap()
                .add(BoundingBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, BoundingBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, BoundingBoxLayout.createSequentialGroup()
                            .add(47, 47, 47)
                            .add(BoundingBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(NorthLat2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(NorthLat))
                            .add(144, 144, 144)
                            .add(BoundingBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(SouthLat)
                                .add(SouthLat2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(74, 74, 74)
                            .add(BoundingBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(GetBoundSites)
                                .add(getCoordFile))
                            .addContainerGap())
                        .add(BoundingBoxLayout.createSequentialGroup()
                            .add(121, 121, 121)
                            .add(BoundingBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(WestLon2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(WestLon)
                                .add(EastLon)
                                .add(EastLon2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(boundPic)
                            .addContainerGap()))
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Bounding Box", BoundingBox);

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "Code", "Site Name", "Lat (deg:min:sec)", "Lon (deg:min:sec)", "Drainage Area"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        dataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dataTableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(dataTable);
        dataTable.getColumnModel().getColumn(0).setMinWidth(24);
        dataTable.getColumnModel().getColumn(0).setPreferredWidth(24);
        dataTable.getColumnModel().getColumn(0).setMaxWidth(24);
        dataTable.getColumnModel().getColumn(1).setMinWidth(75);
        dataTable.getColumnModel().getColumn(1).setPreferredWidth(75);
        dataTable.getColumnModel().getColumn(1).setMaxWidth(75);
        dataTable.getColumnModel().getColumn(2).setMinWidth(300);
        dataTable.getColumnModel().getColumn(2).setPreferredWidth(450);
        dataTable.getColumnModel().getColumn(2).setMaxWidth(800);
        dataTable.getColumnModel().getColumn(3).setMinWidth(110);
        dataTable.getColumnModel().getColumn(3).setPreferredWidth(110);
        dataTable.getColumnModel().getColumn(3).setMaxWidth(110);
        dataTable.getColumnModel().getColumn(4).setMinWidth(110);
        dataTable.getColumnModel().getColumn(4).setPreferredWidth(110);
        dataTable.getColumnModel().getColumn(4).setMaxWidth(110);
        dataTable.getColumnModel().getColumn(5).setMinWidth(110);
        dataTable.getColumnModel().getColumn(5).setPreferredWidth(110);
        dataTable.getColumnModel().getColumn(5).setMaxWidth(110);

        DownloadData.setText("Download Data");
        DownloadData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DownloadDataMouseReleased(evt);
            }
        });

        SiteCounterInfo.setText("There are X sites available.");

        EndDate.setText("End Date");

        StartDate.setText("Start Date");

        EndText.setText("2009-05-20");

        StartText.setText("1800-01-01");
        StartText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                StartTextFocusLost(evt);
            }
        });

        CheckAll.setForeground(new java.awt.Color(0, 0, 255));
        CheckAll.setText("Check All");
        CheckAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CheckAllMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CheckAllMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CheckAllMouseReleased(evt);
            }
        });

        UncheckAll.setForeground(new java.awt.Color(0, 0, 255));
        UncheckAll.setText("Uncheck All");
        UncheckAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UncheckAllMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UncheckAllMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                UncheckAllMouseReleased(evt);
            }
        });

        CheckMarked.setForeground(new java.awt.Color(0, 0, 225));
        CheckMarked.setText("Check Unmarked");
        CheckMarked.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CheckMarkedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CheckMarkedMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CheckMarkedMouseReleased(evt);
            }
        });

        Note.setEditable(false);
        Note.setText("NOTE:  Querying many sites and/or a large range of dates may take a long time.  Please be patient.");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(561, Short.MAX_VALUE)
                .add(StartDate)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(StartText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(10, 10, 10)
                .add(EndDate)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(EndText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(DownloadData)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(SiteCounterInfo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(CheckAll, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(UncheckAll, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(CheckMarked, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Note, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 558, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .add(jTabbedPane1)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {EndText, StartText}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 406, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(SiteCounterInfo)
                    .add(CheckAll)
                    .add(UncheckAll)
                    .add(CheckMarked)
                    .add(Note, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(8, 8, 8)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 193, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(DownloadData)
                    .add(EndText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(StartText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(StartDate)
                    .add(EndDate))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *Takes vector from downloaded data and reformats correctly, then displays contents in table.
     * getColumnClass changes the true values into checkboxes.
     * @param myVector
     */
    public void makeTable(Vector<String> myVector) {

        SiteCounterInfo.setText("There are " + myVector.size() + " sites available");
        listOfCheckBoxes = new javax.swing.JCheckBox[myVector.size()];

        Object[][] template = new Object[myVector.size()][5];
        dataTable.setModel(new javax.swing.table.DefaultTableModel(
                template,
                new String[]{
                    "", "Code", "Site Name", "Lat (deg:min:sec)", "Lon(deg:min:sec)", "Drainage Area"}) {

            public Class getColumnClass(int column) {
                try {
                    if (column == 0) {
                        return Class.forName("java.lang.Boolean");
                    }
                    return Class.forName("java.lang.Object");
                } catch (ClassNotFoundException ex) {
                    ex.printStackTrace();
                    return null;
                }
            }
        });
        jScrollPane1.setViewportView(dataTable);

        for (int k = 0; k < myVector.size(); k++) {
            String[] elements = myVector.get(k).toString().split("\t");
            dataTable.selectAll();
            dataTable.clearSelection();

            listOfCheckBoxes[k] = new javax.swing.JCheckBox();
            listOfCheckBoxes[k].setSelected(true);

            dataTable.setValueAt(new Boolean(true), k, 0);
            dataTable.setValueAt(elements[1], k, 1);
            dataTable.setValueAt(elements[2], k, 2);

            String lat = elements[3];
            lat = lat.substring(0, 2) + ":" + lat.substring(2, 4) + ":" + lat.substring(4, 6) + " N";
            dataTable.setValueAt(lat, k, 3);

            String lon = elements[4];
            lon = lon.substring(0, 3) + ":" + lon.substring(3, 5) + ":" + lon.substring(5, 7) + " W";
            dataTable.setValueAt(lon, k, 4);

            if (elements.length == 8) {
                dataTable.setValueAt(elements[7], k, 5);
            } else {
                dataTable.setValueAt("N / A", k, 5);
            }
        }
        TableColumn col1 = dataTable.getColumnModel().getColumn(0);
        TableColumn col2 = dataTable.getColumnModel().getColumn(1);
        TableColumn col3 = dataTable.getColumnModel().getColumn(2);
        TableColumn col4 = dataTable.getColumnModel().getColumn(3);
        TableColumn col5 = dataTable.getColumnModel().getColumn(4);
        TableColumn col6 = dataTable.getColumnModel().getColumn(5);
        col1.setMinWidth(24);
        col1.setMaxWidth(24);
        col1.setPreferredWidth(24);

        col2.setMinWidth(85);
        col2.setMaxWidth(85);
        col2.setPreferredWidth(85);

        col3.setMinWidth(300);
        col3.setMaxWidth(800);
        col3.setPreferredWidth(450);

        col4.setMinWidth(110);
        col4.setMaxWidth(110);
        col4.setPreferredWidth(110);

        col5.setMinWidth(110);
        col5.setMaxWidth(110);
        col5.setPreferredWidth(110);

        col6.setMinWidth(110);
        col6.setMaxWidth(110);
        col6.setPreferredWidth(110);
    }

    private void StartTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_StartTextFocusLost

        if (StartText.getText().equalsIgnoreCase("")) {
            StartText.setText("1800-01-01");
            return;
        } else {
            String[] elements = StartText.getText().split("-");
            if (elements.length == 3) {
                try {
                    java.util.Calendar thisDate = java.util.Calendar.getInstance();
                    thisDate.set(Integer.parseInt(elements[0]), Integer.parseInt(elements[1]), Integer.parseInt(elements[2]));
                } catch (NumberFormatException numberFormatException) {
                    StartText.setText("1800-01-01");
                    return;
                }
            } else {
                StartText.setText("1800-01-01");
                return;
            }
        }
    }//GEN-LAST:event_StartTextFocusLost

    private void dataTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataTableMouseReleased
        System.out.println(java.util.Arrays.toString(dataTable.getSelectedRows()));

        int arr[] = dataTable.getSelectedRows();
        for (int i = 0; i < arr.length; i++) {
            System.out.println(dataTable.getValueAt(arr[i], 0) + " " + dataTable.getValueAt(arr[i], 1));
        }
    }//GEN-LAST:event_dataTableMouseReleased

    private void DownloadDataMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DownloadDataMouseReleased
        int sel = dataTable.getRowCount();
        Boolean check2 = true;

        String[] s = new String[]{StartText.getText(), EndText.getText()};
        Vector v = new Vector();
        Vector v2 = new Vector();
        s[0] = StartText.getText();
        s[1] = EndText.getText();


        javax.swing.JFileChooser fc = new javax.swing.JFileChooser("/");
        fc.setFileSelectionMode(fc.DIRECTORIES_ONLY);
        fc.setDialogTitle("Gauges Directory");
        int result = fc.showDialog(this, "Select");
        java.io.File selectedFile = fc.getSelectedFile();

        if (result == javax.swing.JFileChooser.CANCEL_OPTION) {
            return;
        }

        String[] outputDirs = new String[2];
        outputDirs[0] = selectedFile.getAbsolutePath() + File.separator + "StreamFlow";
        outputDirs[1] = selectedFile.getAbsolutePath() + File.separator + "Stage";

        for (int i = 0; i < 2; i++) {

            boolean success = (new File(outputDirs[i])).mkdirs();
            if (success) {
                System.out.println("Directories: " + outputDirs[i] + " created");
            } else {
                System.out.println("Directories " + outputDirs[i] + " not created");
            }
        }

        for (int j = 0; j < sel; j++) {
            if (dataTable.getValueAt(j, 0).equals(check2)) {
                //String[] codes = new String[]{(dataTable.getValueAt(sel[j], 1))};
                v.addElement(dataTable.getValueAt(j, 1));
                System.out.println(v);
                System.out.println(s.toString());
            }
        }

        try {
            myQueryManager.getData(s, v, outputDirs);
        } catch (IOException ex) {
            Logger.getLogger(TabbedUSGSDownloadWizard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DownloadDataMouseReleased

    private void CheckAllMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckAllMouseReleased
        for (int i = 0; i < dataTable.getRowCount(); i++) {
            dataTable.setValueAt(new Boolean(true), i, 0);
        }
    }//GEN-LAST:event_CheckAllMouseReleased

    private void UncheckAllMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UncheckAllMouseReleased
        for (int i = 0; i < dataTable.getRowCount(); i++) {
            dataTable.setValueAt(new Boolean(false), i, 0);
        }
    }//GEN-LAST:event_UncheckAllMouseReleased

    private void CheckMarkedMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckMarkedMouseReleased
        for (int i = 0; i < dataTable.getRowCount(); i++) {
            dataTable.setValueAt(new Boolean(!((Boolean) dataTable.getValueAt(i, 0))), i, 0);
        }
    }//GEN-LAST:event_CheckMarkedMouseReleased

    private void CheckAllMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckAllMouseEntered
        final String under = "<html><u>Check All</u></html>";
        CheckAll.setText(under);
    }//GEN-LAST:event_CheckAllMouseEntered

    private void CheckAllMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckAllMouseExited
        final String noUnder = "Check All";
        CheckAll.setText(noUnder);
    }//GEN-LAST:event_CheckAllMouseExited

    private void UncheckAllMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UncheckAllMouseEntered
        final String under = "<html><u>Uncheck All</u><html>";
        UncheckAll.setText(under);
    }//GEN-LAST:event_UncheckAllMouseEntered

    private void UncheckAllMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UncheckAllMouseExited
        final String noUnder = "Uncheck All";
        UncheckAll.setText(noUnder);
    }//GEN-LAST:event_UncheckAllMouseExited

    private void CheckMarkedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckMarkedMouseEntered
        final String under = "<html><u>Check Unmarked</u><html>";
        CheckMarked.setText(under);
    }//GEN-LAST:event_CheckMarkedMouseEntered

    private void CheckMarkedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckMarkedMouseExited
        final String noUnder = "Check Unmarked";
        CheckMarked.setText(noUnder);
    }//GEN-LAST:event_CheckMarkedMouseExited

    private void GetBoundSitesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GetBoundSitesMouseReleased
        String west, north, east, south;
        String[] bound = new String[4];

        west = WestLon2.getText();
        north = NorthLat2.getText();
        east = EastLon2.getText();
        south = SouthLat2.getText();
        bound[0] = west;
        bound[1] = north;
        bound[2] = east;
        bound[3] = south;
        //System.out.println(bound);

        Vector face = myQueryManager.filterByLatLon(bound);
        makeTable(face);
}//GEN-LAST:event_GetBoundSitesMouseReleased

    private void getCoordFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getCoordFileActionPerformed
        javax.swing.JFileChooser fc = new javax.swing.JFileChooser("/");
        fc.setFileSelectionMode(fc.FILES_ONLY);
        fc.setDialogTitle("DEM Selection");
        javax.swing.filechooser.FileFilter mdtFilter = new visad.util.ExtensionFileFilter("metaDEM", "Digital Elevation Model");
        fc.addChoosableFileFilter(mdtFilter);
        int result = fc.showDialog(this, "Select");
        if (result == javax.swing.JFileChooser.CANCEL_OPTION) {
            return;
        }
        if (!fc.getSelectedFile().isFile()) {
            return;
        }
        try {
            hydroScalingAPI.io.MetaRaster metaDEM = new hydroScalingAPI.io.MetaRaster(fc.getSelectedFile());
            NorthLat2.setText(Double.toString(metaDEM.getMaxLat()));
            SouthLat2.setText(Double.toString(metaDEM.getMinLat()));
            EastLon2.setText(Double.toString(metaDEM.getMaxLon()));
            WestLon2.setText(Double.toString(metaDEM.getMinLon()));

            System.err.println(metaDEM.getMaxLon());
            System.err.println(metaDEM.getMaxLat());
            System.err.println(metaDEM.getMinLon());
            System.err.println(metaDEM.getMinLat());
        } catch (IOException ex) {
            Logger.getLogger(TabbedUSGSDownloadWizard.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_getCoordFileActionPerformed

    private void WYItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_WYItemStateChanged
        if (WY.isSelected()) {
            System.out.println(WY.isSelected());
            String[][] statesparam = new String[][]{{"WY"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_WYItemStateChanged

    private void WIItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_WIItemStateChanged
        if (WI.isSelected()) {
            System.out.println(WI.isSelected());
            String[][] statesparam = new String[][]{{"WI"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_WIItemStateChanged

    private void WVItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_WVItemStateChanged
       if (WV.isSelected()) {
            System.out.println(WV.isSelected());
            String[][] statesparam = new String[][]{{"WV"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_WVItemStateChanged

    private void WAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_WAItemStateChanged
        if (WA.isSelected()) {
            System.out.println(WA.isSelected());
            String[][] statesparam = new String[][]{{"WA"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_WAItemStateChanged

    private void VAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_VAItemStateChanged
        if (VA.isSelected()) {
            System.out.println(VA.isSelected());
            String[][] statesparam = new String[][]{{"VA"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_VAItemStateChanged

    private void VTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_VTItemStateChanged
        if (VT.isSelected()) {
            System.out.println(VT.isSelected());
            String[][] statesparam = new String[][]{{"VT"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_VTItemStateChanged

    private void UTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_UTItemStateChanged
        if (UT.isSelected()) {
            System.out.println(UT.isSelected());
            String[][] statesparam = new String[][]{{"UT"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_UTItemStateChanged

    private void TXItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TXItemStateChanged
        if (TX.isSelected()) {
            System.out.println(TX.isSelected());
            String[][] statesparam = new String[][]{{"TX"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_TXItemStateChanged

    private void TNItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TNItemStateChanged
        if (TN.isSelected()) {
            System.out.println(TN.isSelected());
            String[][] statesparam = new String[][]{{"TN"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_TNItemStateChanged

    private void SDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SDItemStateChanged
        if (SD.isSelected()) {
            System.out.println(SD.isSelected());
            String[][] statesparam = new String[][]{{"SD"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_SDItemStateChanged

    private void SCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SCItemStateChanged
        if (SC.isSelected()) {
            System.out.println(SC.isSelected());
            String[][] statesparam = new String[][]{{"SC"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_SCItemStateChanged

    private void RIItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RIItemStateChanged
        if (RI.isSelected()) {
            System.out.println(RI.isSelected());
            String[][] statesparam = new String[][]{{"RI"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_RIItemStateChanged

    private void PAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_PAItemStateChanged
        if (PA.isSelected()) {
            System.out.println(PA.isSelected());
            String[][] statesparam = new String[][]{{"PA"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_PAItemStateChanged

    private void ORItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ORItemStateChanged
        if (OR.isSelected()) {
            System.out.println(OR.isSelected());
            String[][] statesparam = new String[][]{{"OR"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_ORItemStateChanged

    private void OKItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_OKItemStateChanged
        if (OK.isSelected()) {
            System.out.println(OK.isSelected());
            String[][] statesparam = new String[][]{{"OK"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_OKItemStateChanged

    private void OHItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_OHItemStateChanged
        if (OH.isSelected()) {
            System.out.println(OH.isSelected());
            String[][] statesparam = new String[][]{{"OH"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_OHItemStateChanged

    private void NDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NDItemStateChanged
        if (ND.isSelected()) {
            System.out.println(ND.isSelected());
            String[][] statesparam = new String[][]{{"ND"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_NDItemStateChanged

    private void NCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NCItemStateChanged
        if (NC.isSelected()) {
            System.out.println(NC.isSelected());
            String[][] statesparam = new String[][]{{"NC"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_NCItemStateChanged

    private void NYItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NYItemStateChanged
        if (NY.isSelected()) {
            System.out.println(NY.isSelected());
            String[][] statesparam = new String[][]{{"NY"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_NYItemStateChanged

    private void NMItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NMItemStateChanged
        if (NM.isSelected()) {
            System.out.println(NM.isSelected());
            String[][] statesparam = new String[][]{{"NM"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_NMItemStateChanged

    private void NJItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NJItemStateChanged
        if (NJ.isSelected()) {
            System.out.println(NJ.isSelected());
            String[][] statesparam = new String[][]{{"NJ"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_NJItemStateChanged

    private void NHItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NHItemStateChanged
        if (NH.isSelected()) {
            System.out.println(NH.isSelected());
            String[][] statesparam = new String[][]{{"NH"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_NHItemStateChanged

    private void NVItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NVItemStateChanged
        if (NV.isSelected()) {
            System.out.println(NV.isSelected());
            String[][] statesparam = new String[][]{{"NV"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_NVItemStateChanged

    private void NEItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NEItemStateChanged
        if (NE.isSelected()) {
            System.out.println(NE.isSelected());
            String[][] statesparam = new String[][]{{"NE"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_NEItemStateChanged

    private void MTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MTItemStateChanged
        if (MT.isSelected()) {
            System.out.println(MT.isSelected());
            String[][] statesparam = new String[][]{{"MT"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_MTItemStateChanged

    private void MOItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MOItemStateChanged
        if (MO.isSelected()) {
            System.out.println(MO.isSelected());
            String[][] statesparam = new String[][]{{"MO"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_MOItemStateChanged

    private void MSItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MSItemStateChanged
        if (MS.isSelected()) {
            System.out.println(MS.isSelected());
            String[][] statesparam = new String[][]{{"MS"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_MSItemStateChanged

    private void MNItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MNItemStateChanged
        if (MN.isSelected()) {
            System.out.println(MN.isSelected());
            String[][] statesparam = new String[][]{{"MN"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_MNItemStateChanged

    private void MIItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MIItemStateChanged
        if (MI.isSelected()) {
            System.out.println(MI.isSelected());
            String[][] statesparam = new String[][]{{"MI"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_MIItemStateChanged

    private void MAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MAItemStateChanged
        if (MA.isSelected()) {
            System.out.println(MA.isSelected());
            String[][] statesparam = new String[][]{{"MA"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_MAItemStateChanged

    private void MDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MDItemStateChanged
        if (MD.isSelected()) {
            System.out.println(MD.isSelected());
            String[][] statesparam = new String[][]{{"MD"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_MDItemStateChanged

    private void MEItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MEItemStateChanged
        if (ME.isSelected()) {
            System.out.println(ME.isSelected());
            String[][] statesparam = new String[][]{{"ME"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_MEItemStateChanged

    private void LAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_LAItemStateChanged
        if (LA.isSelected()) {
            System.out.println(LA.isSelected());
            String[][] statesparam = new String[][]{{"LA"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_LAItemStateChanged

    private void KYItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_KYItemStateChanged
        if (KY.isSelected()) {
            System.out.println(KY.isSelected());
            String[][] statesparam = new String[][]{{"KY"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_KYItemStateChanged

    private void KSItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_KSItemStateChanged
        if (KS.isSelected()) {
            System.out.println(KS.isSelected());
            String[][] statesparam = new String[][]{{"KS"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_KSItemStateChanged

    private void IAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_IAItemStateChanged
        if (IA.isSelected()) {
            System.out.println(IA.isSelected());
            String[][] statesparam = new String[][]{{"IA"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_IAItemStateChanged

    private void INItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_INItemStateChanged
        if (IN.isSelected()) {
            System.out.println(IN.isSelected());
            String[][] statesparam = new String[][]{{"IN"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_INItemStateChanged

    private void ILItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ILItemStateChanged
        if (IL.isSelected()) {
            System.out.println(IL.isSelected());
            String[][] statesparam = new String[][]{{"IL"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_ILItemStateChanged

    private void IDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_IDItemStateChanged
        if (ID.isSelected()) {
            System.out.println(ID.isSelected());
            String[][] statesparam = new String[][]{{"ID"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_IDItemStateChanged

    private void HIItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_HIItemStateChanged
        if (HI.isSelected()) {
            System.out.println(HI.isSelected());
            String[][] statesparam = new String[][]{{"HI"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_HIItemStateChanged

    private void GAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_GAItemStateChanged
        if (GA.isSelected()) {
            System.out.println(GA.isSelected());
            String[][] statesparam = new String[][]{{"GA"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_GAItemStateChanged

    private void FLItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FLItemStateChanged
        if (FL.isSelected()) {
            System.out.println(FL.isSelected());
            String[][] statesparam = new String[][]{{"FL"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_FLItemStateChanged

    private void DCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DCItemStateChanged
        if (DC.isSelected()) {
            System.out.println(DC.isSelected());
            String[][] statesparam = new String[][]{{"DC"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_DCItemStateChanged

    private void DEItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DEItemStateChanged
        if (DE.isSelected()) {
            System.out.println(DE.isSelected());
            String[][] statesparam = new String[][]{{"DE"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_DEItemStateChanged

    private void CTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CTItemStateChanged
        if (CT.isSelected()) {
            System.out.println(CT.isSelected());
            String[][] statesparam = new String[][]{{"CT"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_CTItemStateChanged

    private void COItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_COItemStateChanged
        if (CO.isSelected()) {
            System.out.println(CO.isSelected());
            String[][] statesparam = new String[][]{{"CO"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_COItemStateChanged

    private void CAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CAItemStateChanged
        if (CA.isSelected()) {
            System.out.println(CA.isSelected());
            String[][] statesparam = new String[][]{{"CA"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_CAItemStateChanged

    private void ARItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ARItemStateChanged
        if (AR.isSelected()) {
            System.out.println(AR.isSelected());
            String[][] statesparam = new String[][]{{"AR"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_ARItemStateChanged

    private void AZItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AZItemStateChanged
        if (AZ.isSelected()) {
            System.out.println(AZ.isSelected());
            String[][] statesparam = new String[][]{{"AZ"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_AZItemStateChanged

    private void AKItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AKItemStateChanged
        if (AK.isSelected()) {
            System.out.println(AK.isSelected());
            String[][] statesparam = new String[][]{{"AK"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_AKItemStateChanged

    private void ALItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ALItemStateChanged
        if (AL.isSelected()) {
            System.out.println(AL.isSelected());
            String[][] statesparam = new String[][]{{"AL"}, {"Stream", "Gage Height", "Volume"}};
            Vector myVector = myQueryManager.filterByState(statesparam);
            makeTable(myVector);
        }
    }//GEN-LAST:event_ALItemStateChanged

    private void AllSTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AllSTItemStateChanged
//        System.out.println(AllST.isSelected());
//        AL.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        AK.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        AZ.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        AR.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        CA.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        CO.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        CT.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        DE.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        DC.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        FL.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        GA.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        HI.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        ID.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        IL.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        IN.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        IA.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        KS.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        KY.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        LA.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        ME.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        MD.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        MA.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        MI.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        MN.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        MS.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        MO.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        MT.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        NE.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        NV.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        NH.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        NJ.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        NM.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        NY.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        NC.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        ND.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        OH.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        OK.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        OR.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        PA.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        RI.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        SC.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        SD.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        TN.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        TX.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        UT.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        VT.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        VA.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        WA.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        WV.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        WI.setSelected(AllST.isSelected());
//        System.out.println(AllST.isSelected());
//        WY.setSelected(AllST.isSelected());


        if (AllST.isSelected()) {
            System.out.println(AllST.isSelected());
            String[][] statesparam = new String[][]{{"AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL",
                    "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME",
                    "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH",
                    "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI",
                    "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI",
                    "WY"}, {"Stream", "Gage Height", "Volume"}};
        java.util.Vector myVector = myQueryManager.filterByState(statesparam);
        makeTable(myVector);
        }
    }//GEN-LAST:event_AllSTItemStateChanged

    private void AllRegItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AllRegItemStateChanged
        if (AllReg.isSelected()) {
            System.out.println(AllReg.isSelected());
            String[][] statesparam = new String[][]{{"AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL",
                    "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME",
                    "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH",
                    "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI",
                    "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI",
                    "WY"}, {"Stream", "Gage Height", "Volume"}};
        java.util.Vector myVector = myQueryManager.filterByState(statesparam);
        makeTable(myVector);
        }
    }//GEN-LAST:event_AllRegItemStateChanged

    private void WestItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_WestItemStateChanged
        if (West.isSelected()) {
            System.out.println(West.isSelected());
            String[][] statesparam = new String[][]{{"WA", "OR", "CA", "ID", "NV", "MT", "WY", "UT",
                    "AZ", "CO", "NM", "AK", "HI"}, {"Stream", "Gage Height", "Volume"}};
        java.util.Vector myVector = myQueryManager.filterByState(statesparam);
        makeTable(myVector);
        }
    }//GEN-LAST:event_WestItemStateChanged

    private void MidWestItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MidWestItemStateChanged
        if (MidWest.isSelected()) {
            System.out.println(MidWest.isSelected());
            String[][] statesparam = new String[][]{{"WI", "MI", "IL", "IN", "OH",
                    "ND", "SD", "NE", "KS", "MN", "IA", "MO"}, {"Stream", "Gage Height", "Volume"}};
        java.util.Vector myVector = myQueryManager.filterByState(statesparam);
        makeTable(myVector);
        }
    }//GEN-LAST:event_MidWestItemStateChanged

    private void SouthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SouthItemStateChanged
        if (South.isSelected()) {
            System.out.println(South.isSelected());
            String[][] statesparam = new String[][]{{"DE", "MD", "DC", "VA", "WV", "NC", "SC", "GA",
                    "FL", "KY", "TN", "MS", "AL", "OK", "TX", "AR", "LA"}, {"Stream", "Gage Height", "Volume"}};
        java.util.Vector myVector = myQueryManager.filterByState(statesparam);
        makeTable(myVector);
        }
    }//GEN-LAST:event_SouthItemStateChanged

    private void NorthEastItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NorthEastItemStateChanged
        if (NorthEast.isSelected()) {
            System.out.println(NorthEast.isSelected());
            String[][] statesparam = new String[][]{{"ME", "NH", "VT", "MA", "RI",
                    "CT", "NY", "PA", "NJ"}, {"Stream", "Gage Height", "Volume"}};
        java.util.Vector myVector = myQueryManager.filterByState(statesparam);
        makeTable(myVector);
        }
    }//GEN-LAST:event_NorthEastItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        TabbedUSGSDownloadWizard dialog = new TabbedUSGSDownloadWizard(new javax.swing.JFrame(), true);
        System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AK;
    private javax.swing.JCheckBox AL;
    private javax.swing.JCheckBox AR;
    private javax.swing.JCheckBox AZ;
    private javax.swing.JCheckBox AllReg;
    private javax.swing.JCheckBox AllST;
    private javax.swing.JPanel BoundingBox;
    private javax.swing.JCheckBox CA;
    private javax.swing.JCheckBox CO;
    private javax.swing.JCheckBox CT;
    private javax.swing.JLabel CheckAll;
    private javax.swing.JLabel CheckMarked;
    private javax.swing.JCheckBox DC;
    private javax.swing.JCheckBox DE;
    private javax.swing.JButton DownloadData;
    private javax.swing.JLabel EastLon;
    private javax.swing.JTextField EastLon2;
    private javax.swing.JLabel EndDate;
    private javax.swing.JTextField EndText;
    private javax.swing.JCheckBox FL;
    private javax.swing.JCheckBox GA;
    private javax.swing.JButton GetBoundSites;
    private javax.swing.JCheckBox HI;
    private javax.swing.JCheckBox IA;
    private javax.swing.JCheckBox ID;
    private javax.swing.JCheckBox IL;
    private javax.swing.JCheckBox IN;
    private javax.swing.JCheckBox KS;
    private javax.swing.JCheckBox KY;
    private javax.swing.JCheckBox LA;
    private javax.swing.JCheckBox MA;
    private javax.swing.JCheckBox MD;
    private javax.swing.JCheckBox ME;
    private javax.swing.JCheckBox MI;
    private javax.swing.JCheckBox MN;
    private javax.swing.JCheckBox MO;
    private javax.swing.JCheckBox MS;
    private javax.swing.JCheckBox MT;
    private javax.swing.JPanel Map;
    private javax.swing.JCheckBox MidWest;
    private javax.swing.JCheckBox NC;
    private javax.swing.JCheckBox ND;
    private javax.swing.JCheckBox NE;
    private javax.swing.JCheckBox NH;
    private javax.swing.JCheckBox NJ;
    private javax.swing.JCheckBox NM;
    private javax.swing.JCheckBox NV;
    private javax.swing.JCheckBox NY;
    private javax.swing.JCheckBox NorthEast;
    private javax.swing.JLabel NorthLat;
    private javax.swing.JTextField NorthLat2;
    private javax.swing.JTextField Note;
    private javax.swing.JCheckBox OH;
    private javax.swing.JCheckBox OK;
    private javax.swing.JCheckBox OR;
    private javax.swing.JCheckBox PA;
    private javax.swing.JCheckBox RI;
    private javax.swing.JPanel RegionState;
    private javax.swing.JCheckBox SC;
    private javax.swing.JCheckBox SD;
    private javax.swing.JLabel SiteCounterInfo;
    private javax.swing.JCheckBox South;
    private javax.swing.JLabel SouthLat;
    private javax.swing.JTextField SouthLat2;
    private javax.swing.JLabel StartDate;
    private javax.swing.JTextField StartText;
    private javax.swing.JCheckBox TN;
    private javax.swing.JCheckBox TX;
    private javax.swing.JLabel USGSLegend;
    private javax.swing.JLabel USGSMap;
    private javax.swing.JCheckBox UT;
    private javax.swing.JLabel UncheckAll;
    private javax.swing.JCheckBox VA;
    private javax.swing.JCheckBox VT;
    private javax.swing.JCheckBox WA;
    private javax.swing.JCheckBox WI;
    private javax.swing.JCheckBox WV;
    private javax.swing.JCheckBox WY;
    private javax.swing.JCheckBox West;
    private javax.swing.JLabel WestLon;
    private javax.swing.JTextField WestLon2;
    private javax.swing.JTextArea boundInstruct;
    private javax.swing.JLabel boundPic;
    private javax.swing.JTable dataTable;
    private javax.swing.JButton getCoordFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
