/*
 * ColorTableTribs.java
 *
 * Created on June 14, 2007, 11:01 AM
 */

package hydroScalingAPI.modules.tRIBS_io.widgets;

import java.rmi.RemoteException;
import visad.VisADException;

/**
 *
 * @author  ricardo
 */
public class ColorTableTribs extends javax.swing.JDialog {
    
    /** Creates new form ColorTableTribs */
    public ColorTableTribs(javax.swing.JDialog parent, visad.ScalarMap theMap) {
        super(parent, false);
        initComponents();
        try {
            
            add(new hydroScalingAPI.subGUIs.widgets.RasterPalettesManager(theMap));
        } catch (RemoteException ex) {
            ex.printStackTrace();
        } catch (VisADException ex) {
            ex.printStackTrace();
        }
        
        //Set up general interface
        setTitle("TRIBS Color Table");
        setBounds(0,0, 450, 300);
        java.awt.Rectangle marcoParent=parent.getBounds();
        java.awt.Rectangle thisMarco=this.getBounds();
        setBounds(marcoParent.x+marcoParent.width/2-thisMarco.width/2,marcoParent.y+marcoParent.height/2-thisMarco.height/2,thisMarco.width,thisMarco.height);
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
