/*
 * ReachInfo.java
 *
 * Created on October 6, 2007, 1:12 PM
 */

package hydroScalingAPI.modules.tRIBS_io.widgets;

/**
 *
 * @author  Ricardo Mantilla
 */
public class ReachInfo extends javax.swing.JDialog {
    
    /** Creates new form ReachInfo */
    public ReachInfo(hydroScalingAPI.mainGUI.ParentGUI parent, String message) {
        super(parent, true);
        initComponents();
        hydroScalingAPI.mainGUI.ParentGUI mainFrame=parent;
        
        setBounds(0,0, 400, 350);
        java.awt.Rectangle marcoParent=mainFrame.getBounds();
        java.awt.Rectangle thisMarco=this.getBounds();
        setBounds(marcoParent.x+marcoParent.width/2-thisMarco.width/2,marcoParent.y+marcoParent.height/2-thisMarco.height/2,thisMarco.width,thisMarco.height);
        
        javax.swing.JTextArea licenseText = new javax.swing.JTextArea();
        licenseText.setText(message);
        jScrollPane1.setViewportView(licenseText);
        licenseText.setEditable(false);
        licenseText.setCaretPosition(0);
        jScrollPane1.getVerticalScrollBar().setValue(0);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        doneButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        getContentPane().add(doneButton, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_doneButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doneButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
